//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace yops_ws.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Token
    {
        public int pk { get; set; }
        public string hash { get; set; }
        public int userFk { get; set; }
        public System.DateTime accessTime { get; set; }
    
        public virtual UserAccount UserAccount { get; set; }
    }
}
